version: '3.4'

services:
  localstack:
    image: localstack/localstack:0.12.15
    container_name: localstack
    ports:
      - '4566:4566'
    environment:
      - DEFAULT_REGION=us-east-1
      - SERVICES=sns,sqs,dynamodb,s3,iam,lambda
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'