version: '3.4'

services:
  localstack:
    image: localstack/localstack:2.3.0
    container_name: localstack
    ports:
      - '4566:4566'
    environment:
      - DEFAULT_REGION=us-east-1
      - SERVICES=sns,sqs,dynamodb,s3,iam,lambda,ec2
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - HOSTNAME_EXTERNAL=localhost
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'